### ISSUE TITLE
Server is started but no runners are spawned

### ISSUE THREAD

**Issue by SchoolGuy** [hostinger/fireactions#244]
# Bug Report

## Description

I have installed and configured fireactions; however, no runners are started, and as such, the jobs are never picked up.

## Expected Behavior

Runners are spawned according to the configuration.

## Current Behavior

No runners are spawned.

## Possible Solution

No idea.

## Steps to Reproduce (for bugs)

1. Configure Fireactions to start at least a single runner
2. See none spawned

## Your Environment

* Fireactions version: 0.3.0
* OS: openSUSE Leap 15.6

Configuration file:

```yml
bind_address: 0.0.0.0:8080
metrics:
  enabled: true
  address: 127.0.0.1:8081
github:
  app_id: 1234567
  app_private_key: |
    -----BEGIN RSA PRIVATE KEY-----
    -----END RSA PRIVATE KEY-----
debug: true
pools:
- name: fireactions-performance
  max_runners: 2
  min_runners: 1
  runner:
    name: fireactions-runner
    image: ghcr.io/hostinger/fireactions-images/ubuntu22.04:latest
    image_pull_policy: IfNotPresent
    group_id: 1
    organization: <ORG>
    labels:
    - self-hosted
    - fireactions
  firecracker:
    binary_path: firecracker
    kernel_image_path: /var/lib/fireactions/kernels/5.10/vmlinux
    kernel_args: console=ttyS0 noapic reboot=k panic=1 pci=off nomodules rw
    machine_config:
      mem_size_mib: 4096
      vcpu_count: 4
    metadata:
      example: example
```

Metrics

```
apollo01 (Cobbler GitHub Runner, K3S):~ # curl http://localhost:8081/metrics
# HELP fireactions_pool_current_runners_count Current number of runners in a pool
# TYPE fireactions_pool_current_runners_count gauge
fireactions_pool_current_runners_count{pool="fireactions-performance"} 0
# HELP fireactions_pool_max_runners_count Maximum number of runners in a pool
# TYPE fireactions_pool_max_runners_count gauge
fireactions_pool_max_runners_count{pool="fireactions-performance"} 2
# HELP fireactions_pool_min_runners_count Minimum number of runners in a pool
# TYPE fireactions_pool_min_runners_count gauge
fireactions_pool_min_runners_count{pool="fireactions-performance"} 1
# HELP fireactions_pool_status Status of a pool. 0 is paused, 1 is active.
# TYPE fireactions_pool_status gauge
fireactions_pool_status{pool="fireactions-performance"} 1
# HELP fireactions_pool_total Total number of pools
# TYPE fireactions_pool_total gauge
fireactions_pool_total 1
# HELP fireactions_server_up Is the server up
# TYPE fireactions_server_up gauge
fireactions_server_up 1
```

Logs

```
May 04 12:27:20 apollo01 systemd[1]: Starting Fireactions...
May 04 12:27:20 apollo01 which[14392]: /usr/local/bin/firecracker
May 04 12:27:20 apollo01 which[14395]: /usr/bin/containerd
May 04 12:27:20 apollo01 systemd[1]: Started Fireactions.
May 04 12:27:20 apollo01 fireactions[14397]: 2025-05-04 12:27:20 INF server.go:125 > Starting server on 0.0.0.0:8080 commit=55274d6 date=2025-02-19T09:07:42Z version=0.3.0
May 04 12:27:20 apollo01 fireactions[14397]: 2025-05-04 12:27:20 WRN server.go:127 > Debug mode enabled
May 04 12:27:20 apollo01 fireactions[14397]: 2025-05-04 12:27:20 INF server.go:144 > Pool fireactions-performance started
```
